### PR TITLE
Filter out non-calendar resource types to prevent failure to load objects

### PR DESCRIPTION
**Pull request by robinknox**
When querying iCloud, a number of the "calendar" objects returned are not actually calendars. In order to verify this we need to ensure that a type of "calendar" is included within the resource types returned. When the listCalendars method is called, an error occurs when it runs the supportedReportSet query and receives a 404 in response.

> Error: Bad status: 404 at exports.XMLHttpRequest.request.onreadystatechange (\node_modules\dav\dav.js:3418:27)

I have attached an anonymised JSON response from listCalendars from iCloud. As you can see from the **resourcetype** field, there are several collections here which are **not** calendars and should be excluded from a listCalendars query:

```
[
  {
    "href": "/10002416871/calendars/",
    "props": {
      "displayname": "Robin Knox",
      "getctag": "anonymous",
      "resourcetype": [
        "collection"
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ],
      "syncToken": "anonymous"
    }
  },
  {
    "href": "/10002416871/calendars/15308689-CF01-1536-8AC4-BF990D483C63/",
    "props": {
      "calendarTimezone": "BEGIN:VCALENDAR\r\nVERSION:2.0\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/London\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0000\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nDTSTART:19810329T010000\r\nTZNAME:BST\r\nTZOFFSETTO:+0100\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nDTSTART:19961027T020000\r\nTZNAME:GMT\r\nTZOFFSETTO:+0000\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nEND:VCALENDAR\r\n",
      "displayname": "Calendar",
      "getctag": "anonymous",
      "resourcetype": [
        null,
        "collection",
        "calendar",
        null
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ],
      "syncToken": "anonymous"
    }
  },
  {
    "href": "/10002416871/calendars/home/",
    "props": {
      "displayname": "Home",
      "getctag": "anonymous",
      "resourcetype": [
        null,
        "collection",
        "calendar",
        null
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ],
      "syncToken": "anonymous"
    }
  },
  {
    "href": "/10002416871/calendars/inbox/",
    "props": {
      "getctag": "anonymous",
      "resourcetype": [
        null,
        "collection",
        "schedule-inbox",
        null
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ],
      "syncToken": "anonymous"
    }
  },
  {
    "href": "/10002416871/calendars/notification/",
    "props": {
      "displayname": "notification",
      "getctag": "anonymous",
      "resourcetype": [
        null,
        "collection",
        "notification",
        null
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ],
      "syncToken": "anonymous"
    }
  },
  {
    "href": "/10002416871/calendars/tasks/",
    "props": {
      "displayname": "Reminders",
      "getctag": "anonymous",
      "resourcetype": [
        null,
        "collection",
        "calendar",
        null
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ],
      "syncToken": "anonymous"
    }
  },
  {
    "href": "/10002416871/calendars/work/",
    "props": {
      "displayname": "Work",
      "getctag": "anonymous",
      "resourcetype": [
        null,
        "collection",
        "calendar",
        null
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ],
      "syncToken": "anonymous"
    }
  },
  {
    "href": "/10002416871/calendars/outbox/",
    "props": {
      "resourcetype": [
        null,
        "collection",
        "schedule-outbox",
        null
      ],
      "supportedCalendarComponentSet": [
        "Array"
      ]
    }
  }
]
```

**Note: I have also updated the dav.js file using the make script and found that there are some changes which haven't been added to that file yet.**

### CODE REVIEW

**Comment by robinknox** [comment]
Hi @lambdabaa I made this change in my own fork to allow pulling calendar events from iCloud. Is there any chance you can include it within the master repo?

**Comment by lambdabaa** [comment]
Thanks for the patch! I'll do a release this week.

**Comment by robinknox** [comment]
Thanks very much

**Comment by robinknox** [comment]
Hi @lambdabaa any chance you can find some time to do that release to npm?

**Comment by lambdabaa** [comment]
> Hi @lambdabaa any chance you can find some time to do that release to npm?

Done! That's v1.8.0. Thanks again for your patch and sorry for the delay here.

**Pull request merged**
